export default [
  {
    "name": "Business Owners Policy (BOP)",
    "slug": "business-owners-policy-bop",
    "notes": "Also, known as BOP, this is a type of policy that packages together elements from General Liability and Commercial Property. It may also include elements of crime and EPLI, depending on the carrier.  Depending on the eligibility requirements (which vary by carrier). this is a great way for a small or mid-size business to get a variety of protections.",
    "what_is_it": "Also, known as BOP, this is a type of policy that packages together elements from General Liability and Commercial Property. It may also include elements of crime and EPLI, depending on the carrier.  Depending on the eligbility requirements (which vary by carrier). this is a great way for a small or mid-size business to get many of the protections it needs (also listed here) in one policy.",
    "why_get_it": "It's the simplest way to get most if not all the essential coverage you need for your business.",
    "tooltip_key": "insurance_type_business_owners_policy_(bop)",
    "display_order": 1,
    "icon_name": "business_owners_policy_bop",
    "formatted_text": null,
    "recommendable": true
  },
  {
    "name": "General Liability",
    "slug": "general-liability",
    "notes": "General Liability insurance covers claims of bodily injury or other physical injury or property damage. It is frequently offered in a package with Property insurance to protect your business against incidents that may occur on your premises or at other covered locations where you normally conduct business. Commercial General Liability enables your business to continue operations while it faces real or fraudulent claims of certain types of negligence or wrongdoing.... A standard insurance policy issued to business organizations to protect them against liability claims for bodily injury (BI) and property damage (PD) arising out of premises, operations, products, and completed operations; and advertising and personal injury (PI) liability.",
    "what_is_it": "This policy protects your business claims of bodily injury, property damage or advertising and personal injury (aka reputational damage). For example, the oh-so-common \"slip and fall\" claim would be handled under your General Liability policy.",
    "why_get_it": "More likely than not, you have a contract, like a loan or a lease or mortgage, requiring you have General Liablity insurance.  Even if you don't, this is the absolute best measure you can take to make sure you're covered in case of a law suit against your business.",
    "tooltip_key": "insurance_type_general_liability",
    "display_order": 2,
    "icon_name": "general_liability",
    "formatted_text": null,
    "recommendable": true
  },
  {
    "name": "Commercial Building and/or Property",
    "slug": "commercial-building-and-or-property",
    "notes": "Commercial building and/or property insurance protects your business from financial loss by protecting your business’physical assets.  This policy is appropriate for every business, regardless of whether you own or lease your commercial space or work from home. Commercial property insurance plans vary, but are generally categorized by the type of event leading to a loss, and by what specifically is insured (e.g., fire destroying building and contents, storm damaging an outdoor sign). Additional coverages are available that can be added to the policy to cover a wider variety of events leading to a loss (e.g., earthquake coverage) and a wider variety of items to be insured (e.g., valuable papers and records).",
    "what_is_it": "This policy protects the business' assets, and is appropriate  whether you own or lease your space or work from home. It can be customized in two ways: (1) insure more/less property and (2) insure against more/fewer causes of damage (e.g., earthquakes)",
    "why_get_it": "If you have a mortgage or a lease, you are likely required to have property insurance.  Even if you are not, this is the best way to protect the building you are in and the business property you have in case of a natural disaster or some other  accident. And if the business is at fault for property damange?  It helps pay those claims too.",
    "tooltip_key": "insurance_type_commercial_building_and/or_property",
    "display_order": 3,
    "icon_name": "commercial_building_andor_property",
    "formatted_text": null
  },
  {
    "name": "Workers' Compensation",
    "slug": "workers-compensation",
    "notes": "Workers compensation coverage covers lost wages and medical treatment resulting from an employee’s work-related injury or illness. It also covers services needed to help an employee recover and return to work.",
    "what_is_it": "Workers compensation coverage covers lost wages and medical treatment resulting from an employee’s work-related injury or illness. It also covers services needed to help an employee recover and return to work.",
    "why_get_it": "This is the law in all 50 states.  As soon as you have your first non-owner employee, it's time to get Workers Comp insurance.  Not having this insurance can lead to hefty fines, and of course, it means the business has to pay for any workplace injury claims.",
    "tooltip_key": "insurance_type_workers_compensation",
    "display_order": 4,
    "icon_name": "workers_compensation",
    "formatted_text": null,
    "recommendable": true
  },
  {
    "name": "Disability Insurance",
    "slug": "disability-insurance",
    "notes": "Disability Insurance, often called DI or disability income insurance, or income protection, is a form of insurance that insures the beneficiary's earned income against the risk that a disability creates a barrier for a worker to complete the core functions of their work.",
    "what_is_it": "This coverage supports lost wages resulting from a non work-related injury or illness that leads to an employee being unable to carry out their job.",
    "why_get_it": "This is the law in some states, and not having it can lead to hefty fines.",
    "tooltip_key": "insurance_type_disability_insurance",
    "display_order": 5,
    "icon_name": "disability_insurance",
    "formatted_text": null
  },
  {
    "name": "Crime",
    "slug": "crime",
    "notes": "Crime insurance helps you cover losses resulting from criminal acts such as robbery, burglary and other forms of theft. It is also called \"fidelity insurance\". Many businesses purchase crime insurance that allows them to file claims for employee theft or other offenses with the potential to cause financial ruin.",
    "what_is_it": "Crime insurance helps you cover losses resulting from criminal acts such as robbery, burglary and other forms of theft. It is also called \"fidelity insurance.\"",
    "why_get_it": "It may be hard to believe, but burglaries and robberies are not usually covered in other types of policies.  This is the best and only way to recover losses from crime.",
    "tooltip_key": "insurance_type_crime",
    "display_order": 6,
    "icon_name": "crime",
    "formatted_text": null
  },
  {
    "name": "Employee Dishonesty",
    "slug": "employee-dishonesty",
    "notes": "A fidelity bond is a form of insurance protection that covers policyholders for losses that they incur as a result of fraudulent acts by specified individuals. It usually insures a business for losses caused by the dishonest acts of its employees.",
    "what_is_it": "This is a form of insurance protection that covers policyholders for losses that they incur as a result of fraudulent acts by specified individuals. It usually insures a business for losses caused by the dishonest acts of its employees.",
    "why_get_it": "Employee dishonesty happens and can really cost the business.  This is the best way to protect the business against that risk.",
    "tooltip_key": "insurance_type_employee_dishonesty",
    "display_order": 7,
    "icon_name": "employee_dishonesty",
    "formatted_text": null
  },
  {
    "name": "EPLI",
    "slug": "epli",
    "notes": "A type of liability insurance covering wrongful acts arising from the employment process. The most frequent types of claims covered under such policies include: wrongful termination, discrimination, sexual harassment, and retaliation. In addition, the policies cover claims from a variety of other types of inappropriate workplace conduct, including (but not limited to) employment-related: defamation, invasion of privacy, failure to promote, deprivation of a career opportunity, and negligent evaluation. The policies cover directors and officers, management personnel, and employees as insureds. The most common exclusions are for bodily injury (BI), property damage (PD), and intentional/dishonest acts.",
    "what_is_it": "Ever heard of folks suing their employer over wrongful termination, discrimination, sexual harassment, etc.? This is the coverage that helps businesses pay the awarded or settled damages and legal defense cost of such claims.",
    "why_get_it": "These lawsuits occur frequently, and typically settle for hundreds of thousands or millions of dollars. If you do not have EPLI, you could be out of business due to a single disgruntled employee. It's not worth taking the chance.",
    "tooltip_key": "insurance_type_EPLI",
    "display_order": 8,
    "icon_name": "epli",
    "formatted_text": null
  },
  {
    "name": "Cyber Liability & Data Breach",
    "slug": "cyber-liability-data-breach",
    "notes": "A type of insurance designed to cover consumers of technology services or products. More specifically, the policies are intended to cover a variety of both liability and property losses that may result when a business engages in various electronic activities, such as selling on the Internet or collecting data within its internal electronic network.\r\n\r\nMost notably, but not exclusively, cyber and privacy policies cover a business' liability for a data breach in which the firm's customers' personal information, such as Social Security or credit card numbers, is exposed or stolen by a hacker or other criminal who has gained access to the firm's electronic network. The policies cover a variety of expenses associated with data breaches, including: notification costs, credit monitoring, costs to defend claims by state regulators, fines and penalties, and loss resulting from identity theft.\r\n\r\nIn addition, the policies cover liability arising from website media content, as well as property exposures from: (a) business interruption, (b) data loss/destruction, (c) computer fraud, (d) funds transfer loss, and (e) cyber extortion.",
    "what_is_it": "It seems like every day another company is \"hacked\" and a set of customer's information is exposed.  When that happens companies face a ton of various costs (e.g., notification costs, credit monitoring, defending claims by regulators, fines and penalties), and this policy helps pay for those.",
    "why_get_it": "The government fines, potential lawsuits and notification expenses you incur when a cyber attack happens can easily amount to millions.  Cyber liability & data breach insurance is an extremely affordable way to protect your business from these potential costs.",
    "tooltip_key": "insurance_type_cyber_liability_&_data_breach",
    "display_order": 9,
    "icon_name": "cyber_liability__data_breach",
    "formatted_text": null
  },
  {
    "name": "Commercial Auto",
    "slug": "commercial-auto",
    "notes": "Commercial auto insurance, like your personal auto policy, provides similar coverages such as liability, collision, comprehensive, medical payments and uninsured motorist coverage. It is important to remember that your personal auto poicy will not cover damage occuring while the vehicle is in use for business purposes.",
    "what_is_it": "Commercial auto insurance, like your personal auto policy, provides similar coverages such as liability, collision, comprehensive, medical payments and uninsured motorist coverage.",
    "why_get_it": "This is the law.  Any vehicle and driver out on the road must be insured. Keep in mind that any claims that happen while the car is being used for business purposes will not be paid by a personal auto policy. That's why it is so important to make sure you have commercial auto insurance.",
    "tooltip_key": "insurance_type_commercial_auto",
    "display_order": 10,
    "icon_name": "commercial_auto",
    "formatted_text": null
  },
  {
    "name": "Liquor Liability",
    "slug": "liquor-liability",
    "notes": "Any business that sells or serves alcoholic beverages, including restaurants, nightclubs, and bars, can be held liable for damages or injuries caused by intoxicated patrons. This can include damages that result from fights, careless behavior or even automobile accidents. While it may seem logical to place the blame fully on the individual who perpetrated these acts, the establishments that allowed them to become intoxicated are also held largely liable and can be sued for exorbitant sums of money, particularly if resultant injuries are severe or fatal. Fortunately, you can protect your business from large financial losses with a liquor liability insurance policy. These policies are sometimes included with general liability coverage in some business insurance policies, but most often they need to be purchased separately as stand-alone coverage or as a business policy endorsement.",
    "what_is_it": "This policy protects your business in case intoxicated patrons cause damage or injuries to others (e.g., damages from fights, automobile accidents). Unfortunately, these establishments can be held responsible and sued for lots of money.",
    "why_get_it": "Most states require you you have liquor liability insurance if you \"serve, sell or assist in the purchase of alcohol.\" Even if your state does not, you may be required to carry it by another party like a financial institution if you took a business loan or a landlord if you rent your business space.",
    "tooltip_key": "insurance_type_liquor_liability",
    "display_order": 11,
    "icon_name": "liquor_liability",
    "formatted_text": null
  },
  {
    "name": "Professional Liability / E&O",
    "slug": "professional-liability-e-o",
    "notes": "Professional liability (PL) or Errors & Omissions (E&O) protects your business against liability for committing an error or omission in the work you do. For instance, in the medial profession this type of insurance is called \"Medical Malpractice Insurance.\" Generally, such policies are designed to cover financial losses rather than liability for bodily injury and property damage.",
    "what_is_it": "This policy protects your business against liability for committing an error or omission in the work you do. For instance, in the medical profession this type of insurance is called \"Medical Malpractice Insurance.\"",
    "why_get_it": "You may have contracts that require E&O coverage, provide a \"warranty or guarantee,\" or have clauses that require you to \"indemnify or hold harmless\" your clients. If so, Professional Liability is a must-have.  If not, think about the potential for a customer or vendor to sue you in case of an error when considering E&O.",
    "tooltip_key": "insurance_type_professional_liability_/_e&o",
    "display_order": 12,
    "icon_name": "professional_liability__eo",
    "formatted_text": null
  },
  {
    "name": "Directors & Officers Insurance",
    "slug": "directors-officers-insurance",
    "notes": "The personal assets of private companies' directors and officers are at risk from suits by a variety of entities: customers and clients, shareholders, competitors or suppliers, and government agencies. But the greatest number of suits against directors and officers are employment-related lawsuits brought by employees of the company. Directors and Officers insurance is frequently bundled in a package with Employment Practices Liability Insurance (EPLI). Learn more about our D&O policies.",
    "what_is_it": "Those potentially suing your business may go after the personal assets of the company's directors and officers.  This policy helps safeguard those assets.  A D&O policy is often bundled with an EPLI policy.",
    "why_get_it": "When appointing directors or hiring new officers they may demand D&O coverage as a condition of serving or employment because they don't want to put their personal assets at stake. Sometimes outside investors, such as venture capitalists or other banks, will require D&O policies before providing funding.",
    "tooltip_key": "insurance_type_directors_&_officers_insurance",
    "display_order": 13,
    "icon_name": "directors__officers_insurance",
    "formatted_text": null
  },
  {
    "name": "Inland Marine",
    "slug": "inland-marine",
    "notes": "Inland Marine sounds like something you don't need, but you probably do.  This covers goods in transit on land or through water, as well as property of others that is at your premises or being transported to or from your premises.  An Inland Marine policy could be critical to protecting your business property if your business transports property of any kind or has any buildings under construction.",
    "what_is_it": "Inland Marine sounds like something you don't need, but you probably do.  This covers goods in transit on land or through water, as well as property of others that is at your premises or being transported to or from your premises.",
    "why_get_it": "If you move goods for others, you likely have contracts in place that require you to have Inland Marine insurance.  If you are moving your own business' goods, then consider this just as important as property insurance.",
    "tooltip_key": "insurance_type_inland_marine",
    "display_order": 14,
    "icon_name": "inland_marine",
    "formatted_text": null
  },
  {
    "name": "Umbrella Liability",
    "slug": "umbrella-liability",
    "notes": "When the amount of liability coverage provided by your General Liability, Auto Liability, and/or Employer's Liability is not enough, Umbrella or Excess Liability coverage can be the solution. Umbrella coverage can be bundled with a General Liability policy or purchased as a standalone policy.",
    "what_is_it": "When the amount of liability coverage provided by your General Liability, Auto Liability, and/or Employer's Liability is not enough, Umbrella or Excess Liability coverage can be the solution. Umbrella coverage can be bundled with a General Liability policy or purchased as a standalone policy.",
    "why_get_it": "This is a good idea for any business considering the astronimical amounts that may be on the line in a law suit.",
    "tooltip_key": "insurance_type_umbrella_liability",
    "display_order": 15,
    "icon_name": "umbrella_liability",
    "formatted_text": null
  },
  {
    "name": "Public Officials' Liability",
    "slug": "public-officials-liability",
    "notes": "The liability exposure faced by a public official from \"wrongful acts,\" usually defined under public officials liability insurance policies as actual or alleged errors, omissions, misstatements, negligence, or breach of duty in his or her capacity as a public official or employee of the public entity.",
    "what_is_it": "This policy helps cover public officials in case of claims of errors, omissions, misstatements, negligence, or breach of duty.",
    "why_get_it": "This is essential coverage for a public official.  More likely than not, it is a contractual requirement.",
    "tooltip_key": "insurance_type_public_officials'_liability",
    "display_order": 16,
    "icon_name": "public_officials_liability",
    "formatted_text": null
  },
  {
    "name": "Medical Malpractice",
    "slug": "medical-malpractice",
    "notes": "Medical professional liability insurance, sometimes known as medical malpractice insurance, is one type of professional liability insurance which protects physicians and other licensed health care professionals (e.g., dentist, nurse) from liability associated with wrongful practices resulting in bodily injury, medical expenses and property damage, as well as the cost of defending lawsuits related to such claims.",
    "what_is_it": "This coverage protects physicians and other licensed health care professionals (e.g., dentists, nurses) from liability associated with wrongful practices resulting in bodily injury, medical expenses and property damage.",
    "why_get_it": "The potential for a lawsuit in this area is high in your industry, and this coverage helps you pay damages and legal costs.",
    "tooltip_key": "insurance_type_medical_malpractice",
    "display_order": 17,
    "icon_name": "medical_malpractice",
    "formatted_text": null
  },
  {
    "name": "Business Garage",
    "slug": "business-garage",
    "notes": "Small businesses in the auto trade need garage insurance to protect them from a variety risks. Things like injuries, mistakes or property damage",
    "what_is_it": "Small businesses in the auto trade need garage insurance to protect them from a variety risks. Things like injuries, mistakes or property damage",
    "why_get_it": "This is a must-have for any business operating a garage.",
    "tooltip_key": "insurance_type_business_garage",
    "display_order": 18,
    "icon_name": "business_garage",
    "formatted_text": null
  },
  {
    "name": "Farmowners Multi-peril",
    "slug": "farmowners-multi-peril",
    "notes": "Specialized insurance for farm-owners and others in agriculture.  Contains elements of General Liability and Commercial Property among other types of coverages.",
    "what_is_it": "Specialized insurance for farm-owners and others in agriculture.  Contains elements of General Liability and Commercial Property among other types of coverages.",
    "why_get_it": "This is a must-have for any agriculture or farm-related business.",
    "tooltip_key": "insurance_type_farmowners_multi-peril",
    "display_order": 19,
    "icon_name": "farmowners_multi-peril",
    "formatted_text": null
  },
  {
    "name": "Fiduciary Bond",
    "slug": "fiduciary-bond",
    "notes": "Guarantees that the individuals or legal entities appointed by the court to oversee the property of others will execute those appointed duties in good faith and be accountable for any deficits that may occur.",
    "what_is_it": "Guarantees that the individuals or legal entities appointed by the court to oversee the property of others will execute those appointed duties in good faith and be accountable for any deficits that may occur.",
    "why_get_it": "counterfeiting and forgery are real threats to a business accepting cash or checks.  This type of coverage is not found in other policies, so it's a must-have.",
    "tooltip_key": "insurance_type_fiduciary_bond",
    "display_order": 20,
    "icon_name": "fiduciary_bond",
    "formatted_text": null
  },
  {
    "name": "Ocean Marine",
    "slug": "ocean-marine",
    "notes": "Ocean Marine protects cargo, vessels and other items as they are transported across the ocean. Both the vessel owner and the owner of the cargo are covered in this type of insurance. It may also cover items traveling by air and land as well.",
    "what_is_it": "Ocean Marine protects cargo, vessels and other items as they are transported across the ocean. Both the vessel owner and the owner of the cargo are covered in this type of insurance. It may also cover items traveling by air and land as well.",
    "why_get_it": "If you move goods for others, you likely have contracts in place that require you to have Ocean Marine insurance.  If you are moving your own business' goods, then consider this just as important as property insurance.",
    "tooltip_key": "insurance_type_ocean_marine",
    "display_order": 21,
    "icon_name": "ocean_marine",
    "formatted_text": null
  },
  {
    "name": "Motor Carriers Liability and Physical Damage",
    "slug": "motor-carriers-liability-and-physical-damage",
    "notes": "A commercial auto policy introduced by Insurance Services Office, Inc. (ISO), in 1993 to address the needs of the motor carrier (i.e., trucking) industry. Coverages available include auto liability, trailer interchange, and auto physical damage; other coverages are available by endorsement. The policy was developed as an alternative to the truckers policy because of the changes taking place in the industry. That is, the truckers policy is applicable only for \"for-hire\" motor carriers, whereas the motor carrier policy is appropriate for all types of motor carriers—for-hire, private, or a combination of both types of operations.",
    "what_is_it": "This policy is for the trucking industry, primarily, and includes auto liability, trailer interchange, and auto physical damage; other coverages are available by endorsement.",
    "why_get_it": "Given your industry, you likely have contracts that require you to have this coverage.",
    "tooltip_key": "insurance_type_motor_carriers_liability_and_physical_damage",
    "display_order": 22,
    "icon_name": "motor_carriers_liability_and_physical_damage",
    "formatted_text": null
  },
  {
    "name": "Financial Institutions Bond",
    "slug": "financial-institutions-bond",
    "notes": "Used to insure banks and other financial institutions against employee dishonesty, burglary, robbery, forgery, and similar crime exposures.",
    "what_is_it": "Used to insure banks and other financial institutions against employee dishonesty, burglary, robbery, forgery, and similar crime exposures. ",
    "why_get_it": "Employee dishonesty happens and can really cost the business.  This is the best way to protect the business against that risk.",
    "tooltip_key": "insurance_type_financial_institutions_bond",
    "display_order": 23,
    "icon_name": "financial_institutions_bond",
    "formatted_text": null
  },
  {
    "name": "Surety Bond",
    "slug": "surety-bond",
    "notes": "A surety bond is three-party bond that guarantees the principal will perform the obligations set forth by the obligee or else the surety will step in to help the obligee recuperate losses.",
    "what_is_it": "A surety bond is a three-party bond that guarantees the principal will perform the obligations set forth by the obligee or else the surety will step in to help the obligee recuperate losses.",
    "why_get_it": "This is most often required in a business contract.",
    "tooltip_key": "insurance_type_surety_bond",
    "display_order": 24,
    "icon_name": "surety_bond",
    "formatted_text": null
  },
  {
    "name": "Forgery or Alteration",
    "slug": "forgery-or-alteration",
    "notes": "A specific type of banking liability insurance coverage. A commercial forgery policy protects the insured from any counterfeit checks that are passed to it. Retailers often take out this type of coverage in order to protect themselves from check kiters.",
    "what_is_it": "A specific type of banking liability insurance coverage. A commercial forgery policy protects the insured from any counterfeit checks that are passed to it. Retailers often take out this type of coverage in order to protect themselves from check kiters.",
    "why_get_it": "Counterfeiting and forgery are real threats to a business accepting cash or checks.  This type of coverage is not found in other policies, so it's a must-have.",
    "tooltip_key": "insurance_type_forgery_or_alteration",
    "display_order": 25,
    "icon_name": "forgery_or_alteration",
    "formatted_text": null
  },
  {
    "name": "Money Orders and Counterfeit Money",
    "slug": "money-orders-and-counterfeit-money",
    "notes": "Covers loss due to acceptance of a money order that was issued (or is purported to have been issued) by a post office or express company and loss due to acceptance of counterfeit paper currency of the United States or Canada.",
    "what_is_it": "Covers loss due to acceptance of a money order that was issued (or is purported to have been issued) by a post office or express company and loss due to acceptance of counterfeit paper currency of the United States or Canada.",
    "why_get_it": "Counterfeiting and forgery are real threats to a business accepting cash or checks.  This type of coverage is not found in other policies, so it's a must-have.",
    "tooltip_key": "insurance_type_money_orders_and_counterfeit_money",
    "display_order": 26,
    "icon_name": "money_orders_and_counterfeit_money",
    "formatted_text": null
  },
  {
    "name": "Golf Carts",
    "slug": "golf-carts",
    "notes": "Portection for you (third parties) and your vehicle",
    "what_is_it": "Protection for you (third parties) and your vehicle",
    "why_get_it": "This is must-have for any business operating golf carts.",
    "tooltip_key": "insurance_type_golf_carts",
    "display_order": 27,
    "icon_name": "golf_carts",
    "formatted_text": null
  },
  {
    "name": "Aircraft Liability",
    "slug": "aircraft-liability",
    "notes": "Aircraft liability insurance protects you in the event you are liable if your aircraft injures another or damages their property. ",
    "what_is_it": "Aircraft liability insurance protects you in the event that you are liable if your aircraft injures another or damages their property. ",
    "why_get_it": "This is a good idea for any business operating aircraft.",
    "tooltip_key": "insurance_type_aircraft_liability",
    "display_order": 28,
    "icon_name": "aircraft_liability",
    "formatted_text": null
  },
  {
    "name": "Exhibitions",
    "slug": "exhibitions",
    "notes": "This coverage protects your investment in your event. It allows the organizer to return all or apart of the exhibition or attendance fees, pay incurred expenses and keep the event profit",
    "what_is_it": "This coverage protects your investment in your event. It allows the organizer to return all or part of the exhibition or attendance fees, pay incurred expenses and keep the event profit",
    "why_get_it": "If you're business is hosting an event, your general liablity may not cover potential claims.  That is why most businesses elect to get Exhibitions coverage for special events.",
    "tooltip_key": "insurance_type_exhibitions",
    "display_order": 29,
    "icon_name": "exhibitions",
    "formatted_text": null
  },
  {
    "name": "Warehouse Operators' Legal Liability",
    "slug": "warehouse-operators-legal-liability",
    "notes": "Insurance coverage against liability that might be incurred by businesses that store property of others for a fee. Previously referred to as warehousemen's legal liability insurance.",
    "what_is_it": "Insurance coverage against liability that might be incurred by businesses that store property of others for a fee. Previously referred to as warehousemen's legal liability insurance.",
    "why_get_it": "This is a must-have for any business operating a warehouse storing others' property.",
    "tooltip_key": "insurance_type_warehouse_operators'_legal_liability",
    "display_order": 30,
    "icon_name": "warehouse_operators_legal_liability",
    "formatted_text": null
  },
  {
    "name": "Hangarkeepers Legal Liability",
    "slug": "hangarkeepers-legal-liability",
    "notes": "Provides coverage for damage to or destruction of the aircraft of others while in the insured's custody for storage, repair, or safekeeping and while in or on the scheduled premises.",
    "what_is_it": "Provides coverage for damage to or destruction of the aircraft of others while in the insured's custody for storage, repair, or safekeeping and while in or on the scheduled premises.",
    "why_get_it": "This is a must-have for any business operating an aircraft hanger for others' aricraft.",
    "tooltip_key": "insurance_type_hangarkeepers_legal_liability",
    "display_order": 31,
    "icon_name": "hangarkeepers_legal_liability",
    "formatted_text": null
  },
  {
    "name": "Aviation General Liability Coverage",
    "slug": "aviation-general-liability-coverage",
    "notes": "Commercial general liability coverage for all types of airport exposures.",
    "what_is_it": "Commercial general liability coverage for all types of airport exposures.",
    "why_get_it": "This is essential insurance for airport operators.",
    "tooltip_key": "insurance_type_aviation_general_liability_coverage",
    "display_order": 32,
    "icon_name": "aviation_general_liability_coverage",
    "formatted_text": null
  },
  {
    "name": "Bailees' Customers",
    "slug": "bailees-customers",
    "notes": "Bailee's Customers Insurance'\r\nInsurance coverage for legal liability resulting from damage or destruction of a bailor's property while temporarily under the care or custody of a bailee. A bailee is a person or organization that has temporary possession of someone else's personal property (dry cleaner, parking valet, jewelers, repairers, etc.)",
    "what_is_it": "What's a bailee, you ask?  It's a person or organization that has temporary posession of someone's property (like a dry cleaner). This protects a business like that from liability resulting in damage or destruction to someone else's property while its under their care.",
    "why_get_it": "In the event that your business damages a customer's property while its in your possession, there is potential for that customer to seek damages.  Bailees' is the coverage that helps settle those claims.",
    "tooltip_key": "insurance_type_bailees'_customers",
    "display_order": 33,
    "icon_name": "bailees_customers",
    "formatted_text": null
  },
  {
    "name": "Guests' Property",
    "slug": "guests-property",
    "notes": "Commercial coverage form for the property of hotel or motel guests. Two forms exist: One covers property placed inside a safe deposit box on the premises, and the other covers the legal liability of the company for losses incurred on their premises or damages done to property while in the insured's possession.",
    "what_is_it": "This policy is for hotels or motels to protect them in the case that their guests' property is damaged while on premise.",
    "why_get_it": "This is a must-have for any hotel or motel operator",
    "tooltip_key": "insurance_type_guests'_property",
    "display_order": 34,
    "icon_name": "guests_property",
    "formatted_text": null
  },
  {
    "name": "Environmental Impairment",
    "slug": "environmental-impairment",
    "notes": "A specialized insurance policy that covers liability and sometimes cleanup costs associated with pollution.",
    "what_is_it": "A specialized insurance policy that covers liability and sometimes cleanup costs associated with pollution.",
    "why_get_it": "The potential for a lawsuit in this area is high in your industry, and this coverage helps you pay damages and legal costs.",
    "tooltip_key": "insurance_type_environmental_impairment",
    "display_order": 35,
    "icon_name": "environmental_impairment",
    "formatted_text": null
  },
  {
    "name": "Product Recall",
    "slug": "product-recall",
    "notes": "Insurance coverage for the cost of getting a defective product back under the control of the manufacturer or merchandiser that would be responsible for possible bodily injury (BI) or property damage (PD) from its continued use or existence. Standard product liability insurance does not cover this exposure due to the \"sistership liability exclusion.\"",
    "what_is_it": "This policy covers the cost of getting a defective product (causing bodily injury or property damage) back under the control of the manufacturer/merchandiser. It's important to understand this type of protection is not included in a General Liability policy.",
    "why_get_it": "The potential for a lawsuit in this area is high in your industry, and this coverage helps you pay damages and legal costs.",
    "tooltip_key": "insurance_type_product_recall",
    "display_order": 36,
    "icon_name": "product_recall",
    "formatted_text": null
  },
  {
    "name": "Employee Benefits Liability",
    "slug": "employee-benefits-liability",
    "notes": "Liability of an employer for an error or omission in the administration of an employee benefit program, such as failure to advise employees of benefit programs. Coverage of this exposure is usually provided by endorsement to the general liability policy but may also be provided by a fiduciary liability policy.",
    "what_is_it": "Employers can be held accountable for the benefits  they offer employees. If they are acused of errors, omissions or breach of duties, this coverage helps cover the business. Note that it is sometimes available through endorsement of Genera Liability policy or as a Fiduciary Liability policy.",
    "why_get_it": "Lawsuits of this nature do happen.  And given the amounts involved in employee benefits (think retirement accounts, etc.), the damages can be large. This helps protect the business by paying those claims.",
    "tooltip_key": "insurance_type_employee_benefits_liability",
    "display_order": 37,
    "icon_name": "employee_benefits_liability",
    "formatted_text": null
  },
  {
    "name": "Health Insurance",
    "slug": "health-insurance",
    "notes": "Health Insurance helps you keep your employees healthy and happy.",
    "what_is_it": "Health Insurance helps you keep your employees healthy and happy.",
    "why_get_it": "Health insurance is an optional benefit for employers to provide (except in the state of Hawaii), but it can be of critical importance to current and potential new employees.  Many companies find that the ability to attract and retain talent, keep employees health and earn tax benefits are worth the cost.",
    "tooltip_key": null,
    "display_order": 38,
    "icon_name": "health_insurance",
    "formatted_text": null
  }
];